"$schema" = 'https://starship.rs/config-schema.json'

# Blank line between prompts
add_newline = true

# Show username@hostname like rohit@codebit
[username]
show_always = true
style_user = 'bold blue'
format = '[$user](bold blue)'

[hostname]
ssh_only = false
style = 'bold yellow'
format = '@[$hostname](bold yellow) '

# Directory style with emoji ğŸŒ
[directory]
style = 'bold cyan'
format = 'ğŸ“ [$path](bold cyan) '
truncation_length = 3
truncation_symbol = 'â€¦'

# Git branch module
[git_branch]
symbol = 'ğŸŒ¿ '
style = 'bold purple'
format = '[\($symbol$branch\)]($style) '

# Time module â°
[time]
disabled = false
format = '[â° $time](bold green) '
time_format = "%H:%M:%S"

# Character âœ Green/Red
[character]
success_symbol = '[âœ](bold green)'
error_symbol = '[ğŸš¨](bold red)'

# Package disabled
[package]
disabled = true
